export { default as DetalleScreen } from './detalle-informe'
export { default as ListadoInfosScreen } from './listado-informes'
export { default as NuevoInfoScreen } from './nuevo-informe'
export { default as LoginScreen} from './login'
export { default as RegisterScreen} from './register'
